### ISSUE TITLE
Memory usage way higher than expected when querying CloudWatch logs

### ISSUE THREAD

**Issue by bpringe** [cognitect-labs/aws-api#119]
## Dependencies

My dependencies were as follows:

``` clojure
[com.cognitect.aws/api "0.8.391" :exclusions [org.clojure/clojure]]
[com.cognitect.aws/endpoints "1.1.11.670"]
[com.cognitect.aws/logs "770.2.568.0"]
```

## Description with failing test case

I have a long-running job that pulls logs from CloudWatch using FilterLogEvents. Here's the code, though running it to repro would require pulling actual logs. Also, outside of this function I was closing the client after the call to this function with `stop` to release resources.

```clojure
(defn get-log-events
  [client filter-pattern start-time end-time]
  (let [request {:startTime start-time
                 :endTime end-time
                 :logGroupName "kube-prod"
                 :logStreamNames ["pipeline"]
                 :filterPattern filter-pattern}]
    (loop [log-events []
           response (aws/invoke client {:op :FilterLogEvents
                                        :request request})]
      (when (:cognitect.anomalies/category response)
        (throw (Exception. (str "An error occurred while retrieving logs: " response))))
      (if-let [next-token (:nextToken response)]
        (recur (concat log-events (:events response))
               (aws/invoke client
                           {:op :FilterLogEvents
                            :request (assoc request
                                            :nextToken next-token)}))
        (concat log-events (:events response))))))
```

The issue is that memory would increase up to 10GiB+ when running in our kubernetes cluster (on AWS, where requests to CloudWatch were much faster than running locally, where I didn't see this issue much if at all). While I was pulling in a lot of log data, I partitioned by time periods that made sense, and was not holding onto references of previous requests, so memory never should have been going that high.

I tried also using one client throughout the entire process and that caused memory to increase much more quickly. **My main point here is that when I switched out this lib in this function with amazonica (which uses the Java SDK), without modifying any calling code (period for logs, frequency of calling this function, etc.), memory never went above 600MiB throughout the whole process (where it went to 10GiB+ before).**

I'm wondering if this lib's client is holding onto references somewhere unnecessarily, or doing something in some manner that is memory-inefficient.

**Comment by ghadishayban** [comment]
@bpringe not saying that this is what you're running into, but this is definitely a problem with the code you posted:
https://stuartsierra.com/2015/04/26/clojure-donts-concat

**Comment by bpringe** [comment]
Thanks! I was not aware of this. While I don't think this is my issue, as you said, (never ran into a StackOverFlowError), I am interested in refactoring it to use `into` instead of `concat` to see if it reduces the memory usage even more (after using amazonica).

**Comment by dchelimsky** [comment]
@bpringe do you see the same issue with `com.cognitect.aws/api "0.8.423"`?

**Comment by bpringe** [comment]
@dchelimsky We've since moved that particular code away from using the cognitect aws api, so I'd have to add it back to run a test. That wouldn't be too hard though, and I could try it some time next week.

**Comment by dchelimsky** [comment]
Thanks @bpringe. We'll have a new release very soon, so maybe it's better to wait for that one. I'll circle back here after the release. Thanks for being willing to help.

**Comment by dchelimsky** [comment]
@bpringe I just released 0.8.430. Let me know if you have time to take a look.

**Comment by bpringe** [comment]
I've been at this for a while thinking I must be making some small mistake in my code. I added the dependencies back to my code (updated versions):

```clojure
[com.cognitect.aws/api "0.8.430"]
[com.cognitect.aws/endpoints "1.1.11.718"]
[com.cognitect.aws/logs "785.2.601.0"]
```

Now I always get 0 log events in the response, but nextToken exists in the response, and I add it to the next request, and still get 0 log events. This happens over and over so my code runs in an endless loop. Passing the same parameters to the current version of my code (using amazonica, same aws region, etc), I get log-events as expected, so it seems not to be anything to do with the request parameters.

```clojure
;; snippet of the code being run
([client filter-pattern start-time end-time acc-fn]
   (let [op-map {:op :FilterLogEvents
                 :request {:starTime start-time
                           :endTime end-time
                           :logGroupName "kube-prod"
                           :logStreamNames ["pipeline"]
                           :filterPattern filter-pattern}}]
     (log/debug "Starting get-log-events...")
     (loop [log-events nil
            response (aws/invoke client op-map)]
       (log/debug "response:" (dissoc response :events))
       (if-let [next-token (:nextToken response)]
         (do
           (log/debug "next-token exists:" next-token)
           (log/debug (count (:events response)) "log events received, continuing...")
           (recur (acc-fn log-events (:events response))
                  (let [op-map (assoc-in op-map [:request :nextToken] next-token)]
                    (log/debug "Making new request:" op-map)
                    (aws/invoke client op-map))))
         (do
           (log/debug "All log events have been received!")
           (acc-fn log-events (:events response)))))))
```

Logs:

```
Starting get-log-events...
response: {:searchedLogStreams [{:logStreamName "pipeline", :searchedCompletely false}], :nextToken "zpUlahi1iz0r54spQh9r4QWXO50Q6ouHAYNnuGyV5ko63IZpEYCC24pyR_k5orf8oEuf1zHXAaPURLiXlTeyUDCoXSz8oXb4cc2VTioKnlZxmZqdZtlRxfv0n2RL3OdVkyGljECH-NV82ies0DknA4vDR6d-jtxRbzTagAZ6mbcf-ePArpDgu0xvyD5ni1p_KPDFppX6_yqyokfuxMsjMAQpMUAbAgNLqx_IGgZELE8ybu8A8FeXZBvfQlj92Qkt"}
next-token exists: zpUlahi1iz0r54spQh9r4QWXO50Q6ouHAYNnuGyV5ko63IZpEYCC24pyR_k5orf8oEuf1zHXAaPURLiXlTeyUDCoXSz8oXb4cc2VTioKnlZxmZqdZtlRxfv0n2RL3OdVkyGljECH-NV82ies0DknA4vDR6d-jtxRbzTagAZ6mbcf-ePArpDgu0xvyD5ni1p_KPDFppX6_yqyokfuxMsjMAQpMUAbAgNLqx_IGgZELE8ybu8A8FeXZBvfQlj92Qkt
0 log events received, continuing...
Making new request: {:op :FilterLogEvents, :request {:starTime 1581292800000, :endTime 1581379199999, :logGroupName "kube-prod", :logStreamNames ["pipeline"], :filterPattern "{($.kubernetes.namespace_name = *twitter* || $.kubernetes.labels.app = *twitter*) && ($.log = *ERROR* || $.log = *Exception*) && ($.log = *aborted-reason* || $.log = *FailedSocialNetworkPostRequest*)}", :nextToken "zpUlahi1iz0r54spQh9r4QWXO50Q6ouHAYNnuGyV5ko63IZpEYCC24pyR_k5orf8oEuf1zHXAaPURLiXlTeyUDCoXSz8oXb4cc2VTioKnlZxmZqdZtlRxfv0n2RL3OdVkyGljECH-NV82ies0DknA4vDR6d-jtxRbzTagAZ6mbcf-ePArpDgu0xvyD5ni1p_KPDFppX6_yqyokfuxMsjMAQpMUAbAgNLqx_IGgZELE8ybu8A8FeXZBvfQlj92Qkt"}}
response: {:searchedLogStreams [{:logStreamName "pipeline", :searchedCompletely false}], :nextToken "zpUlahi1iz0r54spQh9r4QWXO50Q6ouHAYNnuGyV5krSKJXpnmmqpjGBpD1n519AR2e1pemRB-ESJ1miOVE-G_3IiJeQYUQ3hNqwWkRz67Vg5oLZMZ1JACqfr6kCijTej_Ew82Rz1mx39eNoP4rIMrqde9Iu6f38CcWL3OS_gq10eE38MWwMVFSN0zRF5bx9fznZi61wGV5MQiu_4AnFjUGWY8LaOl1Q33nMEVOeA3sSCoRcH-9MI50_ZxWxDxEK"}
next-token exists: zpUlahi1iz0r54spQh9r4QWXO50Q6ouHAYNnuGyV5krSKJXpnmmqpjGBpD1n519AR2e1pemRB-ESJ1miOVE-G_3IiJeQYUQ3hNqwWkRz67Vg5oLZMZ1JACqfr6kCijTej_Ew82Rz1mx39eNoP4rIMrqde9Iu6f38CcWL3OS_gq10eE38MWwMVFSN0zRF5bx9fznZi61wGV5MQiu_4AnFjUGWY8LaOl1Q33nMEVOeA3sSCoRcH-9MI50_ZxWxDxEK
0 log events received, continuing...
Making new request: {:op :FilterLogEvents, :request {:starTime 1581292800000, :endTime 1581379199999, :logGroupName "kube-prod", :logStreamNames ["pipeline"], :filterPattern "{($.kubernetes.namespace_name = *twitter* || $.kubernetes.labels.app = *twitter*) && ($.log = *ERROR* || $.log = *Exception*) && ($.log = *aborted-reason* || $.log = *FailedSocialNetworkPostRequest*)}", :nextToken "zpUlahi1iz0r54spQh9r4QWXO50Q6ouHAYNnuGyV5krSKJXpnmmqpjGBpD1n519AR2e1pemRB-ESJ1miOVE-G_3IiJeQYUQ3hNqwWkRz67Vg5oLZMZ1JACqfr6kCijTej_Ew82Rz1mx39eNoP4rIMrqde9Iu6f38CcWL3OS_gq10eE38MWwMVFSN0zRF5bx9fznZi61wGV5MQiu_4AnFjUGWY8LaOl1Q33nMEVOeA3sSCoRcH-9MI50_ZxWxDxEK"}}
response: {:searchedLogStreams [{:logStreamName "pipeline", :searchedCompletely false}], :nextToken "zpUlahi1iz0r54spQh9r4QWXO50Q6ouHAYNnuGyV5kpSVTAVM4S2MvkljnCxwG9HiYNJYg7bAJM24BzMZ7l-PTRlell6WrYcxJzrdy7z57aPFCFOoh0cQB24QDCsxVtMgn6n5BcGdHvjvxqmRrx9A26-4LdYallq8j2bqB2pxZukyi4dqLGWIfvDr0vjAjU0a4xnR4GUcNDDw1C_iPwe4dKc7I3ywrPeLluDWCcgKrNGmFshuVQg6WDI_1lMIYGf"}
next-token exists: zpUlahi1iz0r54spQh9r4QWXO50Q6ouHAYNnuGyV5kpSVTAVM4S2MvkljnCxwG9HiYNJYg7bAJM24BzMZ7l-PTRlell6WrYcxJzrdy7z57aPFCFOoh0cQB24QDCsxVtMgn6n5BcGdHvjvxqmRrx9A26-4LdYallq8j2bqB2pxZukyi4dqLGWIfvDr0vjAjU0a4xnR4GUcNDDw1C_iPwe4dKc7I3ywrPeLluDWCcgKrNGmFshuVQg6WDI_1lMIYGf
0 log events received, continuing...
Making new request: {:op :FilterLogEvents, :request {:starTime 1581292800000, :endTime 1581379199999, :logGroupName "kube-prod", :logStreamNames ["pipeline"], :filterPattern "{($.kubernetes.namespace_name = *twitter* || $.kubernetes.labels.app = *twitter*) && ($.log = *ERROR* || $.log = *Exception*) && ($.log = *aborted-reason* || $.log = *FailedSocialNetworkPostRequest*)}", :nextToken "zpUlahi1iz0r54spQh9r4QWXO50Q6ouHAYNnuGyV5kpSVTAVM4S2MvkljnCxwG9HiYNJYg7bAJM24BzMZ7l-PTRlell6WrYcxJzrdy7z57aPFCFOoh0cQB24QDCsxVtMgn6n5BcGdHvjvxqmRrx9A26-4LdYallq8j2bqB2pxZukyi4dqLGWIfvDr0vjAjU0a4xnR4GUcNDDw1C_iPwe4dKc7I3ywrPeLluDWCcgKrNGmFshuVQg6WDI_1lMIYGf"}}
response: {:searchedLogStreams [], :nextToken "zpUlahi1iz0r54spQh9r4QWXO50Q6ouHAYNnuGyV5kpSVTAVM4S2MvkljnCxwG9HiYNJYg7bAJM24BzMZ7l-PTRlell6WrYcxJzrdy7z57aPFCFOoh0cQB24QDCsxVtMgn6n5BcGdHvjvxqmRrx9A26-4LdYallq8j2bqB2pxZsoQdxNyzZ3QH1aSRr0QcupAcUh6COEpzNNzrVEFvkDjiRkiPZuOtvM5KreCksNNIWlD0F-5e5B2REPcQwX9yRg"}
next-token exists: zpUlahi1iz0r54spQh9r4QWXO50Q6ouHAYNnuGyV5kpSVTAVM4S2MvkljnCxwG9HiYNJYg7bAJM24BzMZ7l-PTRlell6WrYcxJzrdy7z57aPFCFOoh0cQB24QDCsxVtMgn6n5BcGdHvjvxqmRrx9A26-4LdYallq8j2bqB2pxZsoQdxNyzZ3QH1aSRr0QcupAcUh6COEpzNNzrVEFvkDjiRkiPZuOtvM5KreCksNNIWlD0F-5e5B2REPcQwX9yRg
0 log events received, continuing...
Making new request: {:op :FilterLogEvents, :request {:starTime 1581292800000, :endTime 1581379199999, :logGroupName "kube-prod", :logStreamNames ["pipeline"], :filterPattern "{($.kubernetes.namespace_name = *twitter* || $.kubernetes.labels.app = *twitter*) && ($.log = *ERROR* || $.log = *Exception*) && ($.log = *aborted-reason* || $.log = *FailedSocialNetworkPostRequest*)}", :nextToken "zpUlahi1iz0r54spQh9r4QWXO50Q6ouHAYNnuGyV5kpSVTAVM4S2MvkljnCxwG9HiYNJYg7bAJM24BzMZ7l-PTRlell6WrYcxJzrdy7z57aPFCFOoh0cQB24QDCsxVtMgn6n5BcGdHvjvxqmRrx9A26-4LdYallq8j2bqB2pxZsoQdxNyzZ3QH1aSRr0QcupAcUh6COEpzNNzrVEFvkDjiRkiPZuOtvM5KreCksNNIWlD0F-5e5B2REPcQwX9yRg"}}
```
 
I don't think I can spend any more time on this, at least for the time being. If you see something wrong with my code that I'm not seeing please let me know.

**Comment by daemianmack** [comment]
@bpringe I notice that your original version of `get-log-events` from 19 days ago used a parameter named `:startTime` for the `FilterLogEvents` op; the version posted yesterday uses a parameter named `:starTime`.

**Comment by bpringe** [comment]
@daemianmack That was it... *face palm*. I fixed it and started the same long-running job as before and so far I've seen the memory stay below 500MiB, so it's looking good. I'll report back probably tomorrow after I see how the whole job went.

**Comment by dchelimsky** [comment]
Good 👁 @daemianmack!

@bpringe thanks for sticking w/ this.

**Comment by ghadishayban** [comment]
@bpringe There is some work that you can reuse [here](https://clojure.atlassian.net/browse/CLJ-2555) that you can reuse to make this whole use-case of paginated APIs easier, including checking for anomalies.  Careful with the continuation tokens in AWS, sometimes they send back `""` as a token on the last page.

```
(defn get-all-log-events
  [client base-request]
  (transduce
   (comp (halt-when :cognitect.anomalies/category)
         (mapcat :events))
   conj
   []
   (iteration
    (fn [token]
      (aws/invoke client {:op :FilterLogEvents
                          :request (cond-> base-request
                                     token (assoc :nextToken token))}))
    :kf (fn [response]
          (when-let [token (:nextToken response)]
            (when-not (string/blank? token)
              token))))))

(get-all-log-events client {:startTime start-time
                            :endTime end-time
                            :logGroupName "kube-prod"
                            :logStreamNames ["pipeline"]
                            :filterPattern filter-pattern})
```

**Comment by bpringe** [comment]
Just FYI, the job finished successfully (no OOM issue). 🎉 I'll close this issue now.

@ghadishayban Thanks for the suggestions!
